---

- name: Install Packages
  apt:
    state: present
    name:
      - ntp
      - ntpstat
      - ntpdate

- name: Update NTP configuration
  template:
    dest: /etc/ntp.conf
    group: root
    owner: root
    mode: 0644
    src: ntp.conf.j2
  register: ntp_config

- name: NTP Service Enable
  service:
    name: ntp
    state: "{{ 'restarted' if ntp_config.changed else 'started' }}"
    enabled: true
